spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    # 热部署开关
    restart:
      enabled: true
  # 控制台输出日志
  output:
    ansi:
      # 日志彩色打印
      enabled: always
  logging:
    level:
      org.springframework:
        security: trace
  thymeleaf:
    cache: false
  jackson:
    serialization:
      indent-output: true
  security:
    user:
      name: panpan
      password: 123123
  # redis配置
  data:
    redis:
      # 地址
      host: 43.142.255.148
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      #    password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# MyBatis
mybatis:
  # 主键自增策略：uuid
  configuration:
    default-id-type: uuid
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.pp.boot.domain.entity

# 应用服务 WEB 访问端口
server:
  port: 8080
  undertow:
    io-threads: 200
    worker-threads: 800
  servlet:
    # 应用的访问路径
    context-path:
# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10
panpan:
  name: panpan

ee-admin:
  name: EE
  version: v1.0.0

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secretKey: XKN3t+21VOjDKgQPAUgYyZcoSGtV44gONm1Z4tgvjN4kGpQDhuO8A/GaVKcRGRCY+E7R582nhvYBJuPhGYnGFQ==
  # 令牌有效期（默认30分钟）
  expireTime: 30


springdoc:
  api-docs:
    # 是否开启接口文档
    enabled: true
  #  swagger-ui:
  #    # 持久化认证数据
  #    persistAuthorization: true
  info:
    # 标题
    title: '标题：${ee-admin.name}管理系统_接口文档'
    # 描述
    description: '描述：用于管理集团旗下公司的人员信息,具体包括XXX,XXX模块...'
    # 版本
    version: '版本号: ${ee-admin.version}'
    # 作者信息
    contact:
      name: pan
      email: supanpan199919@163.com
      url: https://github.com/AtwoodPa/boot_init_template
  components:
    # 鉴权方式配置
    security-schemes:
      apiKey:
        type: APIKEY
        in: HEADER
        name: ${sa-token.token-name}
  #这里定义了两个分组，可定义多个，也可以不定义
  group-configs:
    - group: 1.核心模块
      packages-to-scan: com.pp.boot.demos.web
    - group: 2.测试模块
      packages-to-scan: com.pp.boot.demos.test
    - group: 3.Security模块
      packages-to-scan: com.pp.boot.web.controller.system