# THYMELEAF (ThymeleafAutoConfiguration)
# 开启模板缓存（默认值： true ）
spring:
  security:
    user:
      name: panpan
      password: 123123
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/boot-init?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    validation-query: SELECT 1
    validation-query-timeout: 3000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    remove-abandoned-timeout: 1800
    log-abandoned: true
    filters: stat,wall,log4j

# 下面这些内容是为了让 MyBatis 映射
mybatis:
  # 主键自增策略：uuid
  configuration:
    default-id-type: uuid
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.pp.boot.domain.entity

# 应用服务 WEB 访问端口
server:
  port: 8080
  undertow:
    io-threads: 200
    worker-threads: 800
  servlet:
    # 应用的访问路径
    context-path: /api

panpan:
  name: panpan

